### ISSUE TITLE
提示"提交内容与数据库一致"

### ISSUE THREAD

**Issue by o-liverkk** [EhTagTranslation/Editor#1170]
如图, 这个标签没有被翻译, 但提示与数据库一致, 怎么解?

![image](https://user-images.githubusercontent.com/65083224/214462463-aa03183d-5c5d-4274-905c-9ad010223907.png)

**Comment by o-liverkk** [comment]
![image](https://user-images.githubusercontent.com/65083224/214803395-7dd46348-a3d3-43b8-8fc3-1296d9cb35d1.png)

不知道该提供哪些信息, 所有对原作的提交都会出现这个问题.

**Comment by OpportunityLiu** [comment]
还能复现吗？好像只是服务器抽风
