### ISSUE TITLE
能否自定义新增记录在markdown表格中的位置（行数）

### ISSUE THREAD

**Issue by leonardyan** [EhTagTranslation/Editor#380]
或者准确地说，指定一个已有条目，然后把新条目加到它后面。
原因是，像角色数据库
https://github.com/EhTagTranslation/Database/blob/master/database/character.md
其中的大部分角色都是按照来源作品分组的。然而使用editor新增记录时似乎无法指定新纪录在表格中的位置，这样如果发现某个原作的分组遗漏了某个角色而想要追加，就无法保证新条目还在想要的分组里，就只好自己手动编辑然后PR了

**Comment by OpportunityLiu** [comment]
除了直接去看md文件的人，也没有谁会在意这个顺序了。。。

如果你有这种强迫症，还是直接提交PR吧
