### ISSUE TITLE
模糊R18G失效

### ISSUE THREAD

**Issue by Mapaler** [EhTagTranslation/Editor#585]
这些R18G图只能被R18模糊，不能被R18G模糊。
![Screenshot_2020-12-08-16-32-15](https://user-images.githubusercontent.com/6565860/101459245-fa1a1380-3972-11eb-9f57-eb2a428ade04.png)

**Comment by Mapaler** [comment]
![Screenshot_2020-12-08-16-37-23](https://user-images.githubusercontent.com/6565860/101459834-b4117f80-3973-11eb-940b-80745cb1bd09.png)
这里也不知道为什么不能提交

**Comment by OpportunityLiu** [comment]
![图片](https://user-images.githubusercontent.com/13471233/103071248-32218780-45fe-11eb-92f7-0045bf526db3.png)
这几个命名空间保护了啊，之前讨论过的吧，只能在网页上改艺术家、团队、作品、角色
